title: '[Issue Title] '
labels: ['help']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed description of the issue
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Please add any other context, environment information or screenshots
    validations:
      required: false
